# Generated by Django 4.0.1 on 2022-01-27 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_post_alter_contact_form_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
